# Generated by Django 5.2.6 on 2025-09-15 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('MovieID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(blank=True, max_length=120)),
                ('Actor2Name', models.CharField(blank=True, max_length=120)),
                ('DirectorName', models.CharField(blank=True, max_length=120)),
                ('MovieGenre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Other', 'Other')], default='Other', max_length=20)),
                ('ReleaseYear', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2025)])),
            ],
        ),
    ]
